### ISSUE TITLE
"AsciiBib" syntax for Relaton input

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/relaton#33]
Currently there are two ways of representing a Relaton bib item:
* Relaton YAML
* Relation XML

We have a need to enter arbitrary bib items into Metanorma via an inline format. Since it will be in AsciiDoc syntax we call it "AsciiBib".

This differs from the typical AsciiDoc reference where it uses a list to represent a reference:

```doc
* [[[ANCHOR,CITE-TITLE]]], _title_
```

### Example 1

Relaton YAML from https://github.com/CalConnect/standards.calconnect.org/blob/cbc837c8dd3679b1afd661a63a523a2ef05a5a42/_input/external.yaml#L5-L25

```yaml
docidentifier: CC/S 0505:2005
doctype: specification
title: Results from Recurrence Questionnaire
stage: published
pdf: pubdocs/CD0505%20Results%20from%20First%20Recurrence%20Questionnaire.pdf
revdate: 2005-09-26
abstract: The Recurrence Technical Committee of The Calendaring and Scheduling
  Consortium has collected specific information on how Calendaring and Scheduling
  implementations have, or have not, implemented the Recurrence Rules of RFCs
  2445 and 2446, iCalendar and iTIP. This document is part of the committee's
  work to compile actual usage information and interoperability issues. The Recurrence
  Committee recently collected information in the form of a Recurrence Questionnaire,
  which allowed vendors and other producers and consumers of iCalendar recurrences
  to list the features of iCalendar that they implemented. The questionnaire also
  contained space for comments about each line item in the RFCs and also overall
  issues with recurrences. The Recurrence Technical Committee has since analyzed
  the results of the questionnaire into this document.
technical_committee: RECURRENCE
language: ''
script: ''
datetype: ''
```

In AsciiBib, we can implement this using a combination of the section header (similar to how Metanorma terms and defs), with a definition list, such as:

```adoc
[bibitem]
== Results from Recurrence Questionnaire

ref:: cc0505
docidentifier:: CC/S 0505:2005
doctype:: specification
stage:: published
pdf:: pubdocs/CD0505%20Results%20from%20First%20Recurrence%20Questionnaire.pdf
revdate:: 2005-09-26
abstract:: The Recurrence Technical Committee of The Calendaring and Scheduling
  Consortium has collected specific information on how Calendaring and Scheduling
  implementations have, or have not, implemented the Recurrence Rules of RFCs
  2445 and 2446, iCalendar and iTIP. This document is part of the committee's
  work to compile actual usage information and interoperability issues. The Recurrence
  Committee recently collected information in the form of a Recurrence Questionnaire,
  which allowed vendors and other producers and consumers of iCalendar recurrences
  to list the features of iCalendar that they implemented. The questionnaire also
  contained space for comments about each line item in the RFCs and also overall
  issues with recurrences. The Recurrence Technical Committee has since analyzed
  the results of the questionnaire into this document.
technical_committee:: RECURRENCE
language::
script::
datetype::
```

### Example 2

BibTeX of a NIST publication.

```bibtex
@article{dworkin2016recommendation,
  title={Recommendation for block cipher modes of operation: methods for format-preserving encryption},
  author={Dworkin, Morris},
  journal={NIST Special Publication},
  volume={800},
  pages={38G},
  year={2016}
}
```

```adoc
[bibitem]
== Recommendation for block cipher modes of operation: methods for format-preserving encryption

ref:: dworkin2016recommendation
author:: Dworkin, Morris
series:: NIST Special Publication
docnumber:: 800-38G
year:: 2016
```

In the future, a user can just enter:

```doc
[bibitem]NIST SP 800-38
```

Or something like this for auto-fetching.

Thoughts? @opoudjis @CAMOBAP795 @paolobrasolin @andrew2net
